import ConditionalLayout from "@/components/Layout/ConditionalLayout";
import ChatWidgets from "@/components/shared/ChatWidgets";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Bricolage_Grotesque } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"
  ),
  title: `${process.env.NEXT_PUBLIC_COMPANY_NAME || "Homely"} - ${
    process.env.NEXT_PUBLIC_COMPANY_TAGLINE || "Find Your Dream Home"
  }`,
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.png", type: "image/png", sizes: "192x192" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <NextTopLoader color="#07be8a" />
        <ThemeProvider
          attribute="class"
          enableSystem={true}
          defaultTheme="light"
        >
          <ConditionalLayout>{children}</ConditionalLayout>
          <ChatWidgets />
        </ThemeProvider>
      </body>
    </html>
  );
}
